# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iBV9tlPdT4ltW2goLXBudz0Qv-bR1BaJ
"""

import numpy as numpy
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
newarr = arr.reshape(2,5,2)
print(newarr)